### ISSUE TITLE
Packaged tests hardcode the nested student_onboarding.student_onboarding.* path — 67/70 error in pip-only tenants

### ISSUE THREAD

**Issue by kadaji** [Canusia/package-student_onboarding#1]
The packaged test suite patches module paths under a nested `student_onboarding.student_onboarding.*` prefix, which only resolves in a repo where this package is checked out as an in-tree editable submodule. In a tenant that installs it pip-only, the package is flat (`student_onboarding.api`, not `student_onboarding.student_onboarding.api`), so every affected test errors in `setUp`:

```
AttributeError: module 'student_onboarding' has no attribute 'student_onboarding'
  File ".../student_onboarding/tests.py", line 141, in setUp
    active_term_patcher.start()
```

On `rvcc` (pip-only, v0.0.13): **67 of 70 tests error.**

```
Ran 70 tests in 0.552s
FAILED (errors=67)
```

## Scope

48 patch targets in `tests.py` use the nested prefix, across:

```
student_onboarding.student_onboarding.actions
student_onboarding.student_onboarding.api.active_term
student_onboarding.student_onboarding.management.commands.
student_onboarding.student_onboarding.migrations
student_onboarding.student_onboarding.services
student_onboarding.student_onboarding.services._load_config
student_onboarding.student_onboarding.services.active_term
student_onboarding.student_onboarding.views.active_term
```

## Why it matters

The suite ships inside the wheel, so it is collected by `manage.py test` in any tenant that runs the full suite — it doesn't stay confined to the dev repo. The practical effects:

- Tenants running the full suite get 67 errors that are pure noise, which trains people to ignore the suite's output.
- The package's own tests provide **no** upgrade signal in exactly the deployment shape most tenants use. When bumping `rvcc` to v0.0.13 I could not use them to validate the upgrade at all, and had to verify the two-phase seeding behavior by hand.

## Suggested fix

Resolve the prefix once at module import instead of hardcoding it, mirroring the `find_spec` conditional the apps themselves use for the editable-submodule pattern:

```python
import importlib.util

_PKG = ('student_onboarding.student_onboarding'
        if importlib.util.find_spec('student_onboarding.student_onboarding')
        else 'student_onboarding')

# then: patch(f'{_PKG}.api.active_term', ...)
```

That keeps the tests working in the editable-submodule dev repo and makes them actually run for pip-only tenants.

A reasonable alternative is to exclude tests from the wheel entirely (drop them from `packages`/`MANIFEST.in`), if they're only ever meant to run in the dev repo. Either is fine — the current state is the bad middle, where they ship but cannot pass.

## Found while

Upgrading `rvcc` v0.0.12 → v0.0.13 (Canusia/rvcc#2).
